### ISSUE TITLE
Unable to access properties of COM objects (e.g. Folder, FolderItem etc.)

### ISSUE THREAD

**Issue by fgimian** [microsoft/CsWin32#964]
## Actual behavior

In attempting to obtain a list of Quick Access folder paths using `Shell` and `IShellDispatch`, accessing any `FolderItem` properties results in an exception.

## Expected behavior

I've implemented similar logic using windows-rs and in Go too and in both cases, the properties return the appropriate values correctly.

## Repro steps

1. `NativeMethods.txt` content:
```
Shell
IShellDispatch
Folder
FolderItems
FolderItem
FolderItemVerbs
FolderItemVerb
```

2. `NativeMethods.json` content (if present): N/A

3. Any of your own code that should be shared?

```c#
using Windows.Win32.UI.Shell;

Shell shell = new();
IShellDispatch shellDispatch = (IShellDispatch)shell;
var qaFolder = shellDispatch.NameSpace("shell:::{679f85cb-0220-4080-b29b-5540cc05aab6}");
var qaFolderItems = qaFolder.Items();

for (var i = 0; i < qaFolderItems.Count; i++)
{
    var qaFolderItem = qaFolderItems.Item(i);
    Console.WriteLine(qaFolderItem.Path);
}
```

Exception output is as follows:

```
Unhandled exception. System.InvalidCastException: OleAut reported a type mismatch.
   at Microsoft.Win32.OAVariantLib.ChangeTypeEx(Variant& result, Variant& source, Int32 lcid, IntPtr typeHandle, Int32 cvType, Int16 flags)
   at Microsoft.Win32.OAVariantLib.ChangeType(Variant source, Type targetClass, Int16 options, CultureInfo culture)
   at System.OleAutBinder.ChangeType(Object value, Type type, CultureInfo cultureInfo)
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Object[] aArgs, Boolean[] aArgsIsByRef, Int32[] aArgsWrapperTypes, Type[] aArgsTypes, Type retType)
   at Windows.Win32.UI.Shell.FolderItem.get_Path()
   at Program.<Main>$(String[] args) in C:\Users\Fots\source\QuickAccess\Program.cs:line 11
```

### Context

- CsWin32 version: 0.3.2-beta
- Win32Metadata version (if explicitly set by project): N/A
- Target Framework: net7.0-windows
- `LangVersion` (if explicitly set by project): N/A

Thanks heaps
Fotis

**Comment by fgimian** [comment]
P.S.: My ultimate goal here is to update my Quick Access paths if they differ from the desired set of paths.

Something like this:

```c#
using Windows.Win32.UI.Shell;

var paths = new[]
{
    @"C:\ProgramData",
    @"C:\Users\Fots",
    @"C:\Users\Fots\AppData\Local",
    @"C:\Users\Fots\AppData\Roaming",
    @"C:\Users\Fots\Documents",
    @"C:\Users\Fots\Downloads",
    @"C:\Users\Fots\Music",
    @"C:\Users\Fots\Pictures",
    @"C:\Users\Fots\Source",
    @"C:\Users\Fots\Videos",
};


Shell shell = new();
IShellDispatch shellDispatch = (IShellDispatch)shell;
var qaFolder = shellDispatch.NameSpace("shell:::{679f85cb-0220-4080-b29b-5540cc05aab6}");
var qaFolderItems = qaFolder.Items();

var pinnedPaths = new List<string>();
for (var i = 0; i < qaFolderItems.Count; i++)
{
    var qaFolderItem = qaFolderItems.Item(i);

    if (qaFolderItem.IsFolder == 0)
    {
        continue;
    }

    var qaFolderItemVerbs = qaFolderItem.Verbs();
    var pinned = false;
    for (int j = 0; j < qaFolderItemVerbs.Count; j++)
    {
        var qaFolderItemVerb = qaFolderItemVerbs.Item(j);
        if (qaFolderItemVerb.Name.ToString() == "Unpin from Quick access")
        {
            pinned = true;
            break;
        }
    }

    if (pinned)
    {
        pinnedPaths.Add(qaFolderItem.Path.ToString());
    }
}

if (!pinnedPaths.SequenceEqual(paths))
{
    for (var i = 0; i < qaFolderItems.Count; i++)
    {
        var qaFolderItem = qaFolderItems.Item(i);
        qaFolderItem.InvokeVerb("unpinfromhome");
    }

    foreach (var path in paths)
    {
        var folder = shellDispatch.NameSpace(path);
        var folder2 = (Folder2)folder;
        folder2.Self.InvokeVerb("pintohome");
    }
}
```

**Comment by fgimian** [comment]
This has been working for a while, I honestly can't recall why this wasn't working when I created the issue.

Here's my working code for anyone who is interested:

```c#
﻿using Windows.Win32.Foundation;
using Windows.Win32.UI.Shell;

namespace Oriel.Internal;

internal sealed class QuickAccess
{
    private const string QuickAccessNamespace = "shell:::{679f85cb-0220-4080-b29b-5540cc05aab6}";

    private readonly IShellDispatch _shellDispatch;

    public QuickAccess()
    {
        var shell = new Shell();
        _shellDispatch = (IShellDispatch)shell;
    }

    public List<string> GetPinnedPaths()
    {
        List<string> paths = [];

        var folder = _shellDispatch.NameSpace(QuickAccessNamespace);
        var folderItems = folder.Items();
        for (var i = 0; i < folderItems.Count; i++)
        {
            var folderItem = folderItems.Item(i);
            if (folderItem.IsFolder == VARIANT_BOOL.VARIANT_FALSE)
            {
                continue;
            }

            var pinned = false;

            var folderItemVerbs = folderItem.Verbs();
            for (var j = 0; j < folderItemVerbs.Count; j++)
            {
                var folderItemVerb = folderItemVerbs.Item(j);
                if (folderItemVerb.Name.ToString() == "Unpin from &Quick access")
                {
                    pinned = true;
                    break;
                }
            }

            if (pinned)
            {
                paths.Add(folderItem.Path.ToString());
            }
        }

        return paths;
    }

    public void ClearPinnedPaths()
    {
        var folder = _shellDispatch.NameSpace(QuickAccessNamespace);
        var folderItems = folder.Items();
        for (var i = 0; i < folderItems.Count; i++)
        {
            folderItems.Item(i).InvokeVerb("unpinfromhome");
        }
    }

    public void PinPath(string path)
    {
        var folder = _shellDispatch.NameSpace(path);
        var folder2 = (Folder2)folder;
        folder2.Self.InvokeVerb("pintohome");
    }
}
```

I'll close the issue now😄 

Cheers
Fotis
